# Generated by Django 5.1.2 on 2024-11-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='confirmed_heure',
            field=models.TimeField(blank=True),
        ),
    ]
