# Generated by Django 5.1.2 on 2024-11-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_trip_confirmed_heure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='confirmed_heure',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
